# This example creates two IPA deployments, with one server each.
#
# Note that the hostnames are the same on each deployment, but the domain
# is different, and the name of the servers is also different.
#
# The network is still the same network with mask 255.255.255.0, randomly
# defined as 192.168.X.0/24 (where x is 1-254), and the IP numbers for the
# hosts are in the range 192.168.X.10 to 192.168.x.254.
---
lab_name: multi-deployment
container_fqdn: true
ipa_deployments:
  - name: origin
    domain: origin.ipa.test
    admin_password: SomeADMINpassword
    dm_password: SomeDMpassword
    cluster:
      servers:
        - name: server
          capabilities:
            - CA   # optional, first server is always CA
            - DNS
      clients:
        - name: cli-01
  - name: target
    domain: target.ipa.test
    admin_password: SomeOtherADMINpassword
    dm_password: SomeOtherDMpassword
    cluster:
      servers:
        - name: server
          capabilities:
            - CA   # optional, first server is always CA
            - DNS
      clients:
        - name: cli-01
